import { db, schema } from "./client";

export interface VenueSeedItem {
  id: string;
  name: string;
  area: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  confidence: "high" | "medium" | "low";
  source: string;
  isActive: boolean;
}

export const VENUES_DATA: VenueSeedItem[] = [
  {
    id: "v-the-colosseum-sports-bhavani",
    name: "The Colosseum Sports – Bhavani",
    area: "Komarapalayam",
    address:
      "Komarapalayam, New Bridge Road, near Bhavani New Bus Stand, Bhavani, Tamil Nadu 638301",
    city: "Erode",
    lat: 11.4468,
    lng: 77.6835,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-turf-play-365",
    name: "Turf Play 365",
    area: "Solar",
    address: "Solar, Erode - Karur Main Road, Solar Pudur, Erode, Tamil Nadu 638002",
    city: "Erode",
    lat: 11.3142,
    lng: 77.7541,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-nilgiris-indoor-shuttle-stadium",
    name: "Nilgiris Indoor Shuttle Stadium",
    area: "Perundurai Road",
    address: "Perundurai Road, Teachers Colony, Erode, Tamil Nadu 638011",
    city: "Erode",
    lat: 11.3325,
    lng: 77.7018,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-nilgiris-sports-club",
    name: "Nilgiris Sports Club",
    area: "Perundurai Road",
    address: "Near Collectorate, Perundurai Road, Erode, Tamil Nadu 638011",
    city: "Erode",
    lat: 11.3382,
    lng: 77.7095,
    confidence: "high",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-lets-play-turf-erode",
    name: "Let's Play Turf Erode",
    area: "Thindal",
    address: "Thindal, Erode - Perundurai Road, Erode, Tamil Nadu 638012",
    city: "Erode",
    lat: 11.3218,
    lng: 77.6842,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-playzo-33",
    name: "Playzo 33",
    area: "Villarasampatti",
    address: "Villarasampatti Main Road, Erode, Tamil Nadu 638107",
    city: "Erode",
    lat: 11.3502,
    lng: 77.6894,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-ero-sports-zone",
    name: "Ero Sports Zone",
    area: "BP Agraharam",
    address: "Bhavani Road, BP Agraharam, Erode, Tamil Nadu 638005",
    city: "Erode",
    lat: 11.3654,
    lng: 77.7215,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-samudra-sports-centre",
    name: "Samudra Sports Centre",
    area: "Nasiyanur Road",
    address: "Nasiyanur Road, Erode, Tamil Nadu 638107",
    city: "Erode",
    lat: 11.3415,
    lng: 77.6685,
    confidence: "high",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-choliees-sports",
    name: "Choliees Sports",
    area: "Veerappanchatram",
    address: "Veerappanchatram, Erode, Tamil Nadu 638004",
    city: "Erode",
    lat: 11.3582,
    lng: 77.7128,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-vilvam-sports-turf",
    name: "Vilvam Sports Turf",
    area: "Perundurai",
    address: "Kunnathur Road, Perundurai, Erode, Tamil Nadu 638052",
    city: "Erode",
    lat: 11.2785,
    lng: 77.5852,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-arena-719",
    name: "Arena 719",
    area: "Veerappanchatram",
    address: "Sathy Road, Veerappanchatram, Erode, Tamil Nadu 638004",
    city: "Erode",
    lat: 11.3612,
    lng: 77.7189,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-sixerr-360",
    name: "Sixerr 360",
    area: "Modakkurichi Road",
    address: "Modakkurichi Road, Erode, Tamil Nadu 638104",
    city: "Erode",
    lat: 11.2854,
    lng: 77.7521,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-tiki-taca-turf-erode",
    name: "Tiki Taca Turf Erode",
    area: "Kollampalayam",
    address: "Kollampalayam Bypass Road, Erode, Tamil Nadu 638002",
    city: "Erode",
    lat: 11.3275,
    lng: 77.7382,
    confidence: "high",
    source: "Playo",
    isActive: true,
  },
  {
    id: "v-feather-touch-sportz-academy",
    name: "Feather Touch Sportz Academy",
    area: "Thindal",
    address: "Near Thindal Murugan Temple, Thindal, Erode 638012",
    city: "Erode",
    lat: 11.3245,
    lng: 77.6791,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-akila-sports-arena",
    name: "Akila Sports Arena",
    area: "Kasipalayam",
    address: "Kasipalayam Main Road, Erode, Tamil Nadu 638009",
    city: "Erode",
    lat: 11.3312,
    lng: 77.7345,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-qg-turf",
    name: "QG Turf",
    area: "Surampatti",
    address: "Surampatti Valasu, Erode, Tamil Nadu 638009",
    city: "Erode",
    lat: 11.3289,
    lng: 77.7185,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-sadur-badminton-academy",
    name: "Sadur Badminton Academy",
    area: "Rangampalayam",
    address: "Rangampalayam, Erode, Tamil Nadu 638009",
    city: "Erode",
    lat: 11.3195,
    lng: 77.7248,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-young-india-sports-arena",
    name: "Young India Sports Arena",
    area: "Perundurai Road",
    address: "Perundurai Road, Erode, Tamil Nadu 638011",
    city: "Erode",
    lat: 11.3354,
    lng: 77.6952,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-omg-turf",
    name: "OMG Turf",
    area: "Moolapalayam",
    address: "Moolapalayam Main Road, Erode, Tamil Nadu 638002",
    city: "Erode",
    lat: 11.3182,
    lng: 77.7412,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-athappan-badminton-centre",
    name: "Athappan Badminton Centre",
    area: "Bhavani Road",
    address: "Bhavani Main Road, Erode, Tamil Nadu 638004",
    city: "Erode",
    lat: 11.3712,
    lng: 77.7164,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-ero-sports-academy",
    name: "Ero Sports Academy",
    area: "Kumalan Kuttai",
    address: "Kumalan Kuttai, Erode, Tamil Nadu 638011",
    city: "Erode",
    lat: 11.3395,
    lng: 77.6998,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-cricket-palayam-oval-turf",
    name: "Cricket Palayam Oval Turf",
    area: "Chithode",
    address: "Chithode Road, Erode, Tamil Nadu 638102",
    city: "Erode",
    lat: 11.4125,
    lng: 77.6742,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-the-box-multisport-turf",
    name: "The Box Multisport Turf",
    area: "Thindal",
    address: "Thindal Medu, Erode, Tamil Nadu 638012",
    city: "Erode",
    lat: 11.3178,
    lng: 77.6765,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-qube-sportz-arena",
    name: "Qube Sportz Arena",
    area: "Veerappanchatram",
    address: "Kaikolar Thottam, Erode, Tamil Nadu 638004",
    city: "Erode",
    lat: 11.3542,
    lng: 77.7085,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-sports-village",
    name: "Sports Village",
    area: "Nanjanapuram",
    address: "Nanjanapuram, Erode, Tamil Nadu 638107",
    city: "Erode",
    lat: 11.3365,
    lng: 77.6582,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-tom-and-jerry-sports-arena",
    name: "Tom & Jerry Sports Arena",
    area: "Perundurai",
    address: "Perundurai, Erode, Tamil Nadu 638052",
    city: "Erode",
    lat: 11.2821,
    lng: 77.5914,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-hifi-sports-arena",
    name: "Hifi Sports Arena",
    area: "Solar",
    address: "Solar, Erode, Tamil Nadu 638002",
    city: "Erode",
    lat: 11.3115,
    lng: 77.7592,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-galactic-sportz-turf",
    name: "Galactic Sportz Turf",
    area: "Manickampalayam",
    address: "Manickampalayam, Erode, Tamil Nadu 638004",
    city: "Erode",
    lat: 11.3685,
    lng: 77.7042,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-thindal-badminton-academy",
    name: "Thindal Badminton Academy",
    area: "Thindal",
    address: "Thindal, Erode, Tamil Nadu 638012",
    city: "Erode",
    lat: 11.3262,
    lng: 77.6815,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-elevens-turf",
    name: "Eleven's Turf",
    area: "Chennimalai Road",
    address: "Chennimalai Road, Erode, Tamil Nadu 638001",
    city: "Erode",
    lat: 11.3225,
    lng: 77.7289,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-turfi-33",
    name: "Turfi 33",
    area: "Villarasampatti",
    address: "Villarasampatti Road, Erode, Tamil Nadu 638107",
    city: "Erode",
    lat: 11.3485,
    lng: 77.6854,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-lets-play-sports-turf-34",
    name: "Let's Play Sports Turf - 34",
    area: "Sengodampalayam",
    address: "Sengodampalayam, Erode, Tamil Nadu 638012",
    city: "Erode",
    lat: 11.3155,
    lng: 77.6882,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-greenfield-turf",
    name: "Greenfield Turf",
    area: "Bhavani",
    address: "Bhavani, Erode, Tamil Nadu 638301",
    city: "Erode",
    lat: 11.4395,
    lng: 77.6782,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-akaran-native-sports",
    name: "Akaran Native Sports",
    area: "Suriyampalayam",
    address: "Suriyampalayam, Erode, Tamil Nadu 638316",
    city: "Erode",
    lat: 11.3852,
    lng: 77.7055,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-play-on-turf",
    name: "Play On Turf",
    area: "Chithode",
    address: "Chithode, Erode, Tamil Nadu 638102",
    city: "Erode",
    lat: 11.4185,
    lng: 77.6698,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-friends-club-indoor-shuttle-court",
    name: "Friends Club Indoor Shuttle Court",
    area: "Railway Colony",
    address: "Railway Colony, Erode, Tamil Nadu 638002",
    city: "Erode",
    lat: 11.3321,
    lng: 77.7312,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-majestic-sports-academy",
    name: "Majestic Sports Academy",
    area: "Sampath Nagar",
    address: "Sampath Nagar, Erode, Tamil Nadu 638011",
    city: "Erode",
    lat: 11.3421,
    lng: 77.7065,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-the-turf-station",
    name: "The Turf Station",
    area: "Perundurai",
    address: "Perundurai Bypass, Erode, Tamil Nadu 638052",
    city: "Erode",
    lat: 11.2745,
    lng: 77.5795,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-ms-sports-academy",
    name: "MS Sports Academy",
    area: "Lakkapuram",
    address: "Lakkapuram, Erode, Tamil Nadu 638002",
    city: "Erode",
    lat: 11.2985,
    lng: 77.7654,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-sportz-vibe-multisport-turf",
    name: "Sportz Vibe Multisport Turf",
    area: "Vellode",
    address: "Vellode, Erode, Tamil Nadu 638112",
    city: "Erode",
    lat: 11.2452,
    lng: 77.6521,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
  {
    id: "v-amman-indoor-badminton-court",
    name: "Amman Indoor Badminton Court",
    area: "BP Agraharam",
    address: "B.P. Agraharam, Erode, Tamil Nadu 638005",
    city: "Erode",
    lat: 11.3698,
    lng: 77.7265,
    confidence: "medium",
    source: "Lobbi",
    isActive: true,
  },
];

export async function seedVenues() {
  console.log(`Seeding ${VENUES_DATA.length} venues into NexSport database…`);

  const now = new Date().toISOString();
  let inserted = 0;

  for (const v of VENUES_DATA) {
    db.insert(schema.venues)
      .values({
        id: v.id,
        name: v.name,
        area: v.area,
        address: v.address,
        city: v.city,
        lat: v.lat,
        lng: v.lng,
        confidence: v.confidence,
        source: v.source,
        isActive: v.isActive,
        createdAt: now,
      })
      .onConflictDoUpdate({
        target: schema.venues.id,
        set: {
          name: v.name,
          area: v.area,
          address: v.address,
          city: v.city,
          lat: v.lat,
          lng: v.lng,
          confidence: v.confidence,
          source: v.source,
          isActive: v.isActive,
        },
      })
      .run();

    inserted++;
  }

  console.log(`Successfully seeded ${inserted} venues ✅`);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedVenues()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error("Venues seeding failed", err);
      process.exit(1);
    });
}
