export interface SportRules {
  format: string;
  duration: string;
  rules: string[];
  gear: string[];
}

const fallback: SportRules = {
  format: "Balanced sides, captain-free",
  duration: "60 minutes",
  rules: [
    "Teams are generated by the zig-zag algorithm at lock time.",
    "Result must be confirmed by both sides to count towards Elo.",
    "Fair-play rating is collected from every participant after the match.",
  ],
  gear: ["Sports shoes", "Water bottle"],
};

export const sportRules: Record<string, SportRules> = {
  Badminton: {
    format: "Doubles, best of 3 games",
    duration: "45–60 minutes",
    rules: [
      "Rally scoring to 21, must win by 2 (cap at 30).",
      "Change ends after each game and at 11 in the decider.",
      "Shuttles shared equally between pairs.",
      "Service courts swap on every point won by the serving side.",
    ],
    gear: ["Racquet", "Non-marking shoes", "Feather shuttles"],
  },
  Football: {
    format: "7-a-side, rolling substitutions",
    duration: "2 × 25 minutes",
    rules: [
      "No slide tackles — turf safety rule.",
      "Kick-ins instead of throw-ins; keeper cannot handle back-passes.",
      "Unlimited rolling subs at any stoppage.",
      "Two yellow cards means a 5-minute sin bin.",
    ],
    gear: ["Shin pads", "Turf boots", "Light and dark shirt"],
  },
  Cricket: {
    format: "16 overs a side, hard ball",
    duration: "3 hours",
    rules: [
      "Maximum 4 overs per bowler.",
      "One bouncer per over; wides and no-balls give one extra run.",
      "Fielding restrictions in the first 4 overs.",
      "Neutral umpire arranged by the host.",
    ],
    gear: ["Helmet", "Pads and gloves", "Spikes or trainers"],
  },
  Tennis: {
    format: "Doubles, one set to 6",
    duration: "60–75 minutes",
    rules: [
      "Tie-break at 6-6, first to 7 points.",
      "No-ad scoring at deuce to keep games moving.",
      "Players call their own lines; replay any genuine doubt.",
      "Balls changed after the set.",
    ],
    gear: ["Racquet", "Court shoes", "Fresh ball can"],
  },
  Basketball: {
    format: "5v5, half-court switch",
    duration: "4 × 10 minutes",
    rules: [
      "Make-it-take-it does not apply — possession alternates.",
      "Fouls are self-called; disputed calls go to a replay.",
      "Shot clock of 24 seconds, loosely enforced.",
      "Games decided by 2 clear baskets when scores are level.",
    ],
    gear: ["Indoor shoes", "Reversible jersey"],
  },
};

export function rulesFor(sport: string): SportRules {
  return sportRules[sport] ?? fallback;
}
